# This workflow will build new image and deploy it to Heroku

name: Deploy to Heroku

on:
  push:
    branches:
    - master
env:
  HEROKU_API_KEY:  ${{ secrets.HEROKU_API_KEY }} 

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
       - name: Heroku login
         uses: actions/heroku@1.0.0
         with:
           args: container:login
       
       - name: Heroku push
         uses: actions/heroku@1.0.0
         with:
           args: container:push -a hazard-analysis web
       
       - name: Heroku release
         uses: actions/heroku@1.0.0
         with:
           args: container:release -a hazard-analysis web
