# This workflow will build new image and deploy it to Heroku

name: Deploy to Heroku

on:
  push:
    branches:
    - master
env:
  HEROKU_API_KEY:  ${{ secrets.HEROKU_API_KEY }} 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1      
      - name: Heroku login
        uses: actions/heroku@master
        with:
          args: container:login

      - name: Heroku push
        uses: actions/heroku@master
        with:
          args: container:push -a hazard-analysis web

      - name: Heroku release
        uses: actions/heroku@master
        with:
          args: container:release -a hazard-analysis web
